# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

podBusybox:
  enabled: true

deploymentNginx:
  enabled: true
  replicaCount: 2

deploymentBusybox:
  enabled: false
  replicaCount: 2

serviceBusybox:
  enabled: false

serviceNginx:
  enabled: true

ingressNginx:
  enabled: true