{{- if .Values.ingressNginx.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-nginx-ingress
spec:
  rules:
  - http:
      paths:
      - path: "/nginx"
        backend:
          serviceName: my-nginx-service
          servicePort: 80
      - path: "/todo"
        backend:
          serviceName: todo-app-service
          servicePort: 80
{{- end }}