{{- if .Values.deploymentApache.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  labels:
    app.kubernetes.io/name: php-apache
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: php-apache
  template:
    metadata:
      labels:
        app.kubernetes.io/name: php-apache
    spec:
      containers:
      - name: php-apache
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
          name: "web"
        - containerPort : 3030
          name: "metrics"
        resources:
          requests:
            cpu: "200m"
          limits:
            cpu: "500m"
{{- end }}