{{- if .Values.serviceApache.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
    app.kubernetes.io/name: php-apache
    app.kubernetes.io/version: "1.0.0"
    environment: "staging"
    resdiary.com/scrape-metrics: "true"
spec:
  ports:
  - name: "web"
    port: 80
    targetPort: "web"
  - name: "metrics"
    port : 3030
    targetPort: "metrics"
  selector:
    app.kubernetes.io/name: php-apache
{{- end }}