{{- if .Values.serviceTodoApp.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  labels:
    run: todo-app
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    run: todo-app
{{- end }}